ZimbraOffline/src/java/com/zimbra/cs/offline/jsp/ConsoleBean.java
/*
 * ***** BEGIN LICENSE BLOCK *****
 * Zimbra Collaboration Suite Server
 * Copyright (C) 2007, 2008, 2009, 2010, 2013, 2014 Zimbra, Inc.
 * 
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software Foundation,
 * version 2 of the License.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program.
 * If not, see <http://www.gnu.org/licenses/>.
 * ***** END LICENSE BLOCK *****
 */
package com.zimbra.cs.offline.jsp;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.Date;
import java.util.List;

import com.zimbra.common.service.ServiceException;
import com.zimbra.cs.account.Account;
import com.zimbra.cs.account.DataSource;
import com.zimbra.cs.account.Provisioning;
import com.zimbra.cs.offline.common.OfflineConstants;
import com.zimbra.cs.offline.common.OfflineConstants.SyncStatus;

public class ConsoleBean extends PageBean {
    public class AccountSummary {
        private String id;
        private String type;
        private String flavor;
        private String name;
        private String email;
        private long lastSync;
        private SyncStatus status = SyncStatus.unknown;
        private String errorCode;
        private String errorMsg;
        private String exception;
        private boolean isFirst;

        public String getId() {
            return id;
        }

        public String getType() {
            return type;
        }

        public String getFlavor() {
            return flavor;
        }

        public String getName() {
            return name;
        }

        public String getEmail() {
            return email;
        }

        public Date getLastSync() {
            return lastSync == 0 ? null : new Date(lastSync);
        }

        public SyncStatus getSyncStatus() {
            return status;
        }
        
        public String getErrorCode() {
        	return errorCode;
        }
        
        public String getErrorMsg() {
        	return errorMsg;
        }
        
        public String getException() {
        	return exception;
        }
        
        public String getUserFriendlyErrorMessage() {
        	if (errorCode == null)
        		errorCode = "offline.UNEXPECTED";
        	
        	String msg = getMessage("client." + errorCode, false);
        	if (msg == null)
        		msg = getMessage("exception." + errorCode, false);
        	if (msg == null)
        		msg = getMessage("exception.offline.UNEXPECTED", false);
        	return msg;
        }
        
        public boolean isStatusUnknown() {
            return status == SyncStatus.unknown;
        }

        public boolean isStatusOffline() {
            return status == SyncStatus.offline;
        }

        public boolean isStatusOnline() {
            return status == SyncStatus.online;
        }

        public boolean isStatusRunning() {
            return status == SyncStatus.running;
        }

        public boolean isStatusAuthFailed() {
            return status == SyncStatus.authfail;
        }

        public boolean isStatusError() {
            return status == SyncStatus.error;
        }

        public boolean isFirst() {
            return isFirst;
        }
    }

    // only set for promoting
    private String accountId;
    private String verb;

    private AccountSummary[] savedAccounts;

    public ConsoleBean() {}

    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    public void setVerb(String verb) {
        this.verb = verb;
    }

    public AccountSummary[] getAccounts() throws ServiceException {
        JspProvStub stub = JspProvStub.getInstance();

        String[] order = null;
        if (accountId != null && verb == null) {
            order = stub.promoteAccount(accountId);
            accountId = null;
        } else if (savedAccounts != null)
            return savedAccounts;
        else
            order = stub.getAccountsOrder();

        List<AccountSummary> sums = new ArrayList<AccountSummary>();
        List<Account> accounts = stub.getOfflineAccounts();
        for (Account account : accounts) {
            AccountSummary sum = new AccountSummary();
            sum.id = account.getId();
	    sum.type = "zimbra";
            sum.flavor = account.getAttr(OfflineConstants.A_offlineAccountFlavor);
	    if (sum.flavor == null)
		sum.flavor = "Zimbra";
            sum.name = account.getAttr(Provisioning.A_zimbraPrefLabel);
            sum.name = sum.name != null ? sum.name :
                account.getAttr(OfflineConstants.A_offlineAccountName);
            sum.email = account.getName();
            sum.lastSync = account.getLongAttr(OfflineConstants.A_offlineLastSync, 0);
            String status = account.getAttr(OfflineConstants.A_offlineSyncStatus);
            sum.status = status == null ? SyncStatus.unknown : SyncStatus.valueOf(status);
            sum.errorCode = account.getAttr(OfflineConstants.A_offlineSyncStatusErrorCode);
            sum.errorMsg = account.getAttr(OfflineConstants.A_offlineSyncStatusErrorMsg);
            sum.exception = account.getAttr(OfflineConstants.A_offlineSyncStatusException);
            sums.add(sum);
        }
        List<DataSource> dataSources = stub.getOfflineDataSources();
        for (DataSource ds : dataSources) {
            AccountSummary sum = new AccountSummary();
            sum.id = ds.getAccountId();
            Account account = stub.getOfflineAccount(sum.id);
	    sum.type = ds.getType().toString();
            sum.flavor = ds.getAttr(OfflineConstants.A_offlineAccountFlavor);
	    if (sum.flavor == null) {
		String domain = ds.getAttr(Provisioning.A_zimbraDataSourceDomain, null);
		if (sum.type.equals("pop3"))
		    sum.flavor = "Pop";
		else if (GmailBean.Domain.equals(domain))
		    sum.flavor = "Gmail";
		else if (MmailBean.Domain.equals(domain))
		    sum.flavor = "MSE";
		else if (YmailBean.Domain.equals(domain))
		    sum.flavor = "YMP";
		else
		    sum.flavor = "Imap";
	    }
	        sum.name = account.getAttr(Provisioning.A_zimbraPrefLabel);
	        if (sum.name == null)
	            sum.name = ds.getName();
            sum.email = ds.getEmailAddress();
            sum.lastSync = ds.getLongAttr(OfflineConstants.A_zimbraDataSourceLastSync, 0);
            String status = ds.getAttr(OfflineConstants.A_zimbraDataSourceSyncStatus);
            sum.status = status == null ? SyncStatus.unknown : SyncStatus.valueOf(status);
            sum.errorCode = ds.getAttr(OfflineConstants.A_zimbraDataSourceSyncStatusErrorCode);
            sums.add(sum);
        }

        final String[] finalOrder = order;
        final AccountSummary[] sumArray = new AccountSummary[sums.size()];
        sums.toArray(sumArray);

        if (sumArray.length > 0) {
            Arrays.sort(sumArray, new Comparator<AccountSummary>() {
                public int compare(AccountSummary o1, AccountSummary o2) {
                    int index1 = sumArray.length, index2 = sumArray.length;
                    for (int i = 0; i < finalOrder.length; ++i) {
                        if (o1.id.equals(finalOrder[i]))
                            index1 = i;
                        else if (o2.id.equals(finalOrder[i]))
                            index2 = i;
                    }
                    return index1 - index2;
                }
            });
            sumArray[0].isFirst = true;
        }
        savedAccounts = sumArray;
        return sumArray;
    }
}

ZimbraOffline/src/java/com/zimbra/cs/offline/jsp/PageBean.java
/*
 * ***** BEGIN LICENSE BLOCK *****
 * Zimbra Collaboration Suite Server
 * Copyright (C) 2007, 2008, 2009, 2010, 2011, 2013, 2014 Zimbra, Inc.
 * 
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software Foundation,
 * version 2 of the License.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program.
 * If not, see <http://www.gnu.org/licenses/>.
 * ***** END LICENSE BLOCK *****
 */
package com.zimbra.cs.offline.jsp;

import java.text.MessageFormat;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.MissingResourceException;
import java.util.ResourceBundle;

import javax.servlet.http.HttpServletRequest;

import com.zimbra.common.localconfig.LC;
import com.zimbra.common.service.ServiceException;
import com.zimbra.cs.account.Provisioning;
import com.zimbra.cs.offline.common.OfflineConstants;

public class PageBean {
    private Locale clientLocale = new Locale("en");
    private static Locale serverLocale = null; 
    private static final String APP_VERSION = LC.get("zdesktop_relabel") + LC.get("zdesktop_version") + " (build " + LC.get("zdesktop_buildid") + ")";

    private String getMsgFromBundle(String key) {
        ResourceBundle bundle = ResourceBundle.getBundle("/messages/ZdMsg", clientLocale);
        String msg;
        
        try {
            msg = bundle.getString(key);
        } catch (MissingResourceException x) {
            msg = null;
        }
        return msg;
    }

    protected String getMessage(String key) {
        String msg = getMsgFromBundle(key);
        
        return msg == null ? "??" + key + "??" : msg; 
    }

    protected String getMessage(String key, boolean keyAsDefault) {
        return keyAsDefault ? getMessage(key) : getMsgFromBundle(key);
    }

    protected String getMessage(String key, Object[] params) {
        return MessageFormat.format(getMessage(key), params);
    }

    protected String getMessage(String key, Object[] params, boolean keyAsDefault) {
        if (keyAsDefault)
            return getMessage(key, params);
        String msg = getMsgFromBundle(key);
        return msg == null ? null : MessageFormat.format(msg, params);
    }

    public PageBean() {}

    public String getAppVersion() { return APP_VERSION; }

    public String getLoginUsername() {
        try {
            return JspProvStub.getInstance().getLoginAccountName();
        } catch (ServiceException x) {
            return JspConstants.LOCAL_ACCOUNT;
        }
    }

    public void setLocale(Locale locale) throws ServiceException {
        clientLocale = locale;
        updateServerLocale(locale);
    }

    public String getSkin() {
        try {
            return JspProvStub.getInstance().getOfflineAccount(
                OfflineConstants.LOCAL_ACCOUNT_ID).getAttr(Provisioning.A_zimbraPrefSkin);
        } catch (ServiceException x) {
            return "carbon";
        }
    }

    public static synchronized void updateServerLocale(Locale locale) throws ServiceException {
        if (serverLocale == null || !serverLocale.equals(locale)) { 
            Map<String, Object> attrs = new HashMap<String, Object>();
            attrs.put(Provisioning.A_zimbraPrefLocale, locale.toString());
            JspProvStub stub = JspProvStub.getInstance();
            stub.modifyOfflineAccount(OfflineConstants.LOCAL_ACCOUNT_ID, attrs);
            serverLocale = (Locale)locale.clone();						
        }
    }

    public static String getBaseUri() {
        return "http://127.0.0.1:" + LC.zimbra_admin_service_port.value();
    }

    public static String getLocalConfig(String key) {
        return LC.get(key);
    }

    private static final String[] knownPassThroughFlags = new String[] {"dev","notifydebug","scripterrors"};

    public static String addAuthToken(String url, HttpServletRequest request) {
        String at = LC.get("zdesktop_installation_key");
        
        if (at != null && !at.startsWith("@"))
            url += (url.indexOf('?') < 0 ? "?" : "&") + "at=" + at;
        for (String flagKey : knownPassThroughFlags) {
            String flagVal = request.getParameter(flagKey);
            if (flagVal != null && flagVal.length() > 0) {
                url += (url.indexOf('?') < 0 ? "?" : "&") + flagKey + "=" + flagVal;
            }
        }
        return url;
    }

    public static boolean checkAuthToken(HttpServletRequest request) {
        String key = LC.get("zdesktop_installation_key");
        if (key == null || key.startsWith("@"))
            return true;            
        String at = request.getParameter("at");
        return at != null && at.equals(key);
    }

    public static boolean isPrism(String userAgent) {
        return userAgent != null && userAgent.indexOf("Prism") >= 0;
    }
}

ZimbraOffline/WebRoot/desktop/login.jsp
<!--
 * ***** BEGIN LICENSE BLOCK *****
 * Zimbra Collaboration Suite Server
 * Copyright (C) 2008, 2009, 2010, 2011, 2013, 2014 Zimbra, Inc.
 * 
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software Foundation,
 * version 2 of the License.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program.
 * If not, see <http://www.gnu.org/licenses/>.
 * ***** END LICENSE BLOCK *****
-->
<%@ page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" %>
<%@ page session="false" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="zd" tagdir="/WEB-INF/tags/desktop" %>
<%@ taglib prefix="zdf" uri="com.zimbra.cs.offline.jsp" %>
<%@ taglib prefix="zm" uri="com.zimbra.zm" %>

<jsp:useBean id="bean" class="com.zimbra.cs.offline.jsp.PageBean"/>
<jsp:setProperty name="bean" property="locale" value="${pageContext.request.locale}"/>
<jsp:useBean id="eventBean" class="com.zimbra.cs.offline.jsp.ClientEventBean"/>

<zd:auth/>

${zdf:onLogin(eventBean)}

<c:if test="${empty bean.loginUsername}">
    <c:redirect url="${zdf:addAuthToken('/desktop/console.jsp', pageContext.request)}"/>
</c:if>

<c:set var="attrsToFetch" value="zimbraFeatureMailEnabled,zimbraFeatureCalendarEnabled,zimbraFeatureContactsEnabled,zimbraFeatureIMEnabled,zimbraFeatureNotebookEnabled,zimbraFeatureOptionsEnabled,zimbraFeatureTasksEnabled,zimbraFeatureBriefcasesEnabled"/>
<c:set var="prefsToFetch" value="zimbraPrefSkin,zimbraPrefClientType,zimbraPrefLocale"/>

<c:catch var="loginException">
    <zm:login username="${empty param.username ? bean.loginUsername : param.username}" password="${zdf:getLocalConfig('zdesktop_installation_key')}"
        varRedirectUrl="postLoginUrl" varAuthResult="authResult" rememberme="true"
        prefs="${prefsToFetch}" attrs="${attrsToFetch}" requestedSkin="${param.skin}"/>
</c:catch>

<c:if test="${not empty loginException}">
    <%-- try and use existing cookie if possible --%>
    <c:set var="authtoken" value="${not empty param.zauthtoken ? param.zauthtoken : cookie.ZM_AUTH_TOKEN.value}"/>
    <c:if test="${not empty authtoken}">
        <zm:login authtoken="${authtoken}" authtokenInUrl="${not empty param.zauthtoken}"
            varRedirectUrl="postLoginUrl" varAuthResult="authResult"
            rememberme="true" prefs="${prefsToFetch}" attrs="${attrsToFetch}"
            requestedSkin="${param.skin}"/>
    </c:if>
</c:if>

<c:choose>
<c:when test="${not empty authResult}">
    <jsp:forward page="/desktop/launchZD.jsp"/>
</c:when>
<c:otherwise>
    <c:redirect url="${zdf:addAuthToken('/desktop/console.jsp', pageContext.request)}"/>
</c:otherwise>
</c:choose>

ZimbraOffline/WebRoot/desktop/reject.jsp
<!--
 * ***** BEGIN LICENSE BLOCK *****
 * Zimbra Collaboration Suite Server
 * Copyright (C) 2008, 2009, 2010, 2013, 2014 Zimbra, Inc.
 * 
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software Foundation,
 * version 2 of the License.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program.
 * If not, see <http://www.gnu.org/licenses/>.
 * ***** END LICENSE BLOCK *****
-->
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="fmt" uri="com.zimbra.i18n" %>

<fmt:setBundle basename="/messages/ZdMsg" scope="request"/>
<h3><fmt:message key="UnauthorizedAccess"/></h3>